import React, { useState } from 'react';
import axios from 'axios';
import { Sparkles, Briefcase, BookOpen, Star, AlertCircle } from 'lucide-react';

const AIAdvisor = () => {
  const [interests, setInterests] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [recommendations, setRecommendations] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!interests.trim()) return;

    setLoading(true);
    setError(null);
    setRecommendations(null);

    try {
      const token = localStorage.getItem('token');
      const response = await axios.post(
        '/api/ai-advisor/recommend',
        { interests },
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      );

      setRecommendations(response.data.data);
    } catch (err) {
      console.error(err);
      
      let errorMsg = 'AI recommendation service is currently unavailable. Please try again later.';
      if (err.response?.data) {
        if (err.response.data.errors && err.response.data.errors.length > 0) {
          errorMsg = err.response.data.errors[0].message;
        } else if (err.response.data.message) {
          errorMsg = err.response.data.message;
        }
      }
      
      setError(errorMsg);
    } finally {
      setLoading(false);
    }
  };

  const getPriorityStyle = (priority) => {
    const p = priority.toLowerCase();
    if (p === 'high') {
      return { bg: 'rgba(239, 68, 68, 0.2)', text: 'var(--danger)' };
    } else if (p === 'medium') {
      return { bg: 'rgba(245, 158, 11, 0.2)', text: 'var(--warning)' };
    }
    return { bg: 'rgba(16, 185, 129, 0.2)', text: 'var(--primary-green)' };
  };

  return (
    <div className="fade-in">
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h2>AI Career Advisor <Sparkles size={24} color="var(--primary-purple)" style={{ display: 'inline', verticalAlign: 'middle' }}/></h2>
          <p className="text-secondary">Get personalized career paths, courses, and skills generated by AI.</p>
        </div>
      </header>

      {/* Input Section */}
      <section className="card" style={{ marginBottom: '2rem' }}>
        <form onSubmit={handleSubmit}>
          <div style={{ marginBottom: '1rem' }}>
            <label className="form-label" htmlFor="interests">What are your interests?</label>
            <textarea 
              id="interests"
              className="form-control" 
              rows="4" 
              placeholder="E.g., I love coding, data analysis, and building software..."
              value={interests}
              onChange={(e) => setInterests(e.target.value)}
              disabled={loading}
              minLength="5"
              maxLength="500"
              required
              style={{ resize: 'vertical' }}
            />
          </div>
          <button type="submit" className="btn btn-primary" disabled={loading || interests.length < 5}>
            {loading ? 'Generating...' : 'Generate Recommendations'}
          </button>
        </form>
      </section>

      {/* Error State */}
      {error && (
        <div className="card" style={{ marginBottom: '2rem', borderLeft: '4px solid var(--danger)', backgroundColor: 'rgba(239, 68, 68, 0.1)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--danger)' }}>
            <AlertCircle size={20} />
            <h4 style={{ margin: 0 }}>Error</h4>
          </div>
          <p style={{ marginTop: '0.5rem', marginBottom: 0, color: 'var(--text-primary)' }}>{error}</p>
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div style={{ textAlign: 'center', padding: '3rem' }}>
          <div className="spinner" style={{ margin: '0 auto 1rem', width: '40px', height: '40px', border: '4px solid rgba(255,255,255,0.1)', borderTopColor: 'var(--primary-cyan)', borderRadius: '50%', animation: 'spin 1s linear infinite' }}></div>
          <p className="text-secondary">Analyzing your profile and generating personalized advice...</p>
        </div>
      )}

      {/* Results Section */}
      {recommendations && !loading && (
        <div className="fade-in">
          {/* Disclaimer */}
          <div style={{ padding: '1rem', background: 'rgba(255, 255, 255, 0.05)', borderRadius: '8px', marginBottom: '2rem', fontSize: '0.875rem', color: 'var(--text-secondary)', borderLeft: '3px solid var(--primary-cyan)' }}>
            <strong>Disclaimer:</strong> These are advisory AI-generated suggestions to help guide your studies, and may not reflect specific courses currently available in the UniCoFinder database.
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
            {/* Career Paths */}
            <section>
              <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}><Briefcase size={20} color="var(--primary-cyan)" /> Recommended Career Paths</h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1rem' }}>
                {recommendations.careerPaths?.map((career, index) => (
                  <div key={index} className="card">
                    <h4 className="text-gradient" style={{ marginBottom: '0.5rem' }}>{career.title}</h4>
                    <p style={{ fontSize: '0.9rem', marginBottom: '1rem' }}>{career.description}</p>
                    <div style={{ background: 'rgba(255,255,255,0.05)', padding: '0.75rem', borderRadius: '8px', fontSize: '0.875rem' }}>
                      <strong>Why it matches:</strong> {career.matchReasoning}
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Courses */}
            <section>
              <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}><BookOpen size={20} color="var(--primary-green)" /> Recommended Courses</h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1rem' }}>
                {recommendations.courses?.map((course, index) => (
                  <div key={index} className="card">
                    <h4 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)' }}>{course.name}</h4>
                    <p style={{ fontSize: '0.9rem', marginBottom: '0.5rem', color: 'var(--text-secondary)' }}>{course.relevance}</p>
                    <div style={{ fontSize: '0.875rem', color: 'var(--primary-green)' }}>
                      <strong>Career Link:</strong> {course.relationshipToCareer}
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Skills */}
            <section>
              <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}><Star size={20} color="var(--warning)" /> Key Skills to Develop</h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '1rem' }}>
                {recommendations.skills?.map((skillItem, index) => {
                  const style = getPriorityStyle(skillItem.priority);
                  return (
                  <div key={index} className="card" style={{ display: 'flex', flexDirection: 'column' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.5rem' }}>
                      <h4 style={{ margin: 0 }}>{skillItem.skill}</h4>
                      <span style={{ 
                        fontSize: '0.75rem', 
                        padding: '0.25rem 0.5rem', 
                        borderRadius: '999px', 
                        background: style.bg,
                        color: style.text
                      }}>
                        {skillItem.priority}
                      </span>
                    </div>
                    <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', margin: 0 }}>{skillItem.reason}</p>
                  </div>
                )})}
              </div>
            </section>
          </div>
        </div>
      )}

      {/* keyframes for spin if it's not defined in global css */}
      <style>{`
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

export default AIAdvisor;
